name = "reality-central"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-27"

[[d1_databases]]
binding = "DB"
database_name = "realitycentral-db"
database_id = "REPLACE_WITH_CLOUDFLARE_D1_DATABASE_ID"
