name = "reality-central"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-27"

[[d1_databases]]
binding = "DB"
database_name = "realitycentral-db"
database_id = "211c08f0-af48-40db-903a-4e08a2d85758"
